export type ConnectionStage="Connected"|"Testing prep"|"MCP found"|"Partner outreach"|"Research";
export type Connection={name:string;category:string;stage:ConnectionStage;priority:"P0"|"P1"|"P2";route:string;proof:string;nextAction:string;href:string;updated:string};
export const connections:Connection[]=[
{name:"agent-assistant MCP",category:"Core protocol",stage:"Connected",priority:"P0",route:"Remote MCP / Streamable HTTP",proof:"Public endpoint and seven tools respond in production.",nextAction:"Add OAuth and durable Postgres state.",href:"/developers",updated:"Jul 13, 2026"},
{name:"DeFindex",category:"On-chain finance",stage:"Testing prep",priority:"P0",route:"Stellar API + external wallet signature",proof:"Developer flow reviewed; the docs MCP is informational, not transactional.",nextAction:"Request testnet vault, API access and funding instructions.",href:"https://docs.defindex.io/api-integration-guide/guides-and-tutorials/ai-tools",updated:"Jul 13, 2026"},
{name:"Innovation space",category:"Real-world booking",stage:"Partner outreach",priority:"P0",route:"Hosted catalog + reservation adapter",proof:"Direct founder access is available; service definition is pending.",nextAction:"Confirm day-pass price, availability, cancellation and check-in proof.",href:"#submit-target",updated:"Jul 13, 2026"},
{name:"Task marketplace",category:"Digital work",stage:"Partner outreach",priority:"P1",route:"Marketplace API or hosted connector",proof:"Direct founder access is available; technical interface is pending.",nextAction:"Map task creation, delivery, acceptance and payout states.",href:"#submit-target",updated:"Jul 13, 2026"},
{name:"Travala",category:"Travel",stage:"MCP found",priority:"P1",route:"External MCP for travel discovery",proof:"Travel search is a viable first action; paid booking remains disabled.",nextAction:"Validate tool schemas and run a read-only search dry run.",href:"https://www.travala.com/",updated:"Jul 13, 2026"},
{name:"Amazon Alexa",category:"Voice and home",stage:"Research",priority:"P1",route:"Alexa Custom Skill -> agent-assistant API",proof:"Alexa supports custom skills backed by an HTTPS web service.",nextAction:"Prototype voice intent -> create_intent -> approval handoff.",href:"https://developer.amazon.com/en-US/alexa/alexa-skills-kit/get-deeper/custom-skills",updated:"Jul 13, 2026"},
{name:"Google Home",category:"Voice and home",stage:"Research",priority:"P2",route:"Google Home APIs + mobile authorization",proof:"Home APIs expose devices, structures and automations on Android and iOS.",nextAction:"Assess account linking and whether commerce intents fit Home automations.",href:"https://developers.home.google.com/apis",updated:"Jul 13, 2026"},
{name:"Samsung SmartThings",category:"Voice and home",stage:"Research",priority:"P2",route:"OAuth 2.0 Service Integration",proof:"API Access Apps support discovery, control, status and real-time events.",nextAction:"Define minimum OAuth scopes and callback endpoints.",href:"https://developer.smartthings.com/docs/service-integrations/app-setup",updated:"Jul 13, 2026"},
{name:"Home Assistant",category:"Voice and home",stage:"Research",priority:"P1",route:"Custom integration + Assist intents",proof:"Assist pipelines and custom intent handlers can route voice into one component.",nextAction:"Prototype a local intent handler calling our remote MCP or REST bridge.",href:"https://developers.home-assistant.io/docs/voice/overview/",updated:"Jul 13, 2026"}
];
