export type ConnectionStage =
  | "Connected"
  | "Read-only connected"
  | "Ready to test"
  | "Credentials needed"
  | "Partner outreach"
  | "Research";

export type Connection = {
  name: string;
  focus?: string;
  category: string;
  stage: ConnectionStage;
  priority: "P0" | "P1" | "P2";
  route: string;
  proof: string;
  nextAction: string;
  href: string;
  updated: string;
};

export const connections: Connection[] = [
  {
    name: "DeFindex",
    focus: "Top 1 · active pilot",
    category: "On-chain finance",
    stage: "Credentials needed",
    priority: "P0",
    route: "Stellar API + external wallet signature",
    proof: "API health is live; authenticated testnet vault calls require a DeFindex API key.",
    nextAction: "Request API access, an active testnet vault and token funding instructions.",
    href: "https://docs.defindex.io/api-integration-guide/quickstart",
    updated: "Jul 13, 2026",
  },
  {
    name: "UNBLCK / Tellus Hub",
    focus: "Top 2 · active pilot",
    category: "Local ecosystem",
    stage: "Partner outreach",
    priority: "P0",
    route: "Partner WebMCP -> private access or access request -> assisted onboarding",
    proof: "Direct relationship with the UNBLCK developer and live private-access application flows.",
    nextAction: "Co-design member entry, access requests and the internal onboarding assistant.",
    href: "https://www.unblck.cl/",
    updated: "Jul 13, 2026",
  },
  {
    name: "ArcusX",
    focus: "Top 3 · active pilot",
    category: "Digital work",
    stage: "Partner outreach",
    priority: "P0",
    route: "Partner REST API -> tasks and proposals -> Stellar escrow lifecycle",
    proof: "Authenticated API, developer docs and task, escrow, payment and dispute flows are public; direct contact is available.",
    nextAction: "Request a test API key and confirm the current endpoints, idempotency and webhook contract.",
    href: "https://docs.arcusx.pro/developer-notes/api-integration-guide",
    updated: "Jul 13, 2026",
  },  {
    name: "Travala Travel MCP",
    focus: "Top 4 · active pilot",
    category: "Travel",
    stage: "Read-only connected",
    priority: "P0",
    route: "Remote MCP -> hotel search -> x402 booking",
    proof: "Live handshake, tool discovery, Santiago hotel search and package lookup passed.",
    nextAction: "Build the adapter and confirm a safe test-booking environment before payment.",
    href: "https://www.travala.com/agentic",
    updated: "Jul 13, 2026",
  },
  {
    name: "agent-assistant MCP",
    category: "Core protocol",
    stage: "Connected",
    priority: "P0",
    route: "Remote MCP / Streamable HTTP",
    proof: "Public endpoint and seven tools respond in production.",
    nextAction: "Add OAuth and durable Postgres state.",
    href: "/developers",
    updated: "Jul 13, 2026",
  },
  {
    name: "Chrome WebMCP",
    category: "Core protocol",
    stage: "Ready to test",
    priority: "P0",
    route: "Browser tools / imperative + declarative APIs",
    proof: "Chrome 149 origin trial and local testing flag are documented.",
    nextAction: "Expose one search and one approval tool on our own landing.",
    href: "https://developer.chrome.com/docs/ai/webmcp",
    updated: "Jul 13, 2026",
  },
  {
    name: "Apify MCP",
    category: "Web automation",
    stage: "Read-only connected",
    priority: "P0",
    route: "Remote MCP -> Actor discovery -> approved run",
    proof: "Live MCP handshake and four public discovery tools respond without credentials.",
    nextAction: "Connect OAuth, allowlist two Actors and build a merchant-readiness scan.",
    href: "https://docs.apify.com/integrations/mcp",
    updated: "Jul 13, 2026",
  },
  {
    name: "Shopify Storefront MCP",
    category: "Commerce",
    stage: "Ready to test",
    priority: "P0",
    route: "Per-store UCP/MCP catalog endpoint",
    proof: "Shopify documents unauthenticated storefront catalog, product and policy tools.",
    nextAction: "Connect one dev or partner store and verify search, product detail and policies.",
    href: "https://shopify.dev/docs/apps/build/storefront-mcp/servers/storefront",
    updated: "Jul 13, 2026",
  },
  {
    name: "Shopify UCP Cart + Checkout",
    category: "Commerce",
    stage: "Ready to test",
    priority: "P1",
    route: "UCP cart, checkout handoff and order lifecycle",
    proof: "Current UCP tools support cart creation and checkout handoff for Shopify stores.",
    nextAction: "Use a dev store to test cart idempotency and checkout handoff.",
    href: "https://shopify.dev/docs/agents",
    updated: "Jul 13, 2026",
  },
  {
    name: "x402 Bazaar",
    category: "Payments",
    stage: "Read-only connected",
    priority: "P0",
    route: "Public semantic discovery API + MCP",
    proof: "Live searches returned travel, product and local-business services without authentication.",
    nextAction: "Add discovery-only search with price, network and domain allowlists.",
    href: "https://docs.cdp.coinbase.com/x402/bazaar",
    updated: "Jul 13, 2026",
  },
  {
    name: "x402.org Testnet Facilitator",
    category: "Payments",
    stage: "Ready to test",
    priority: "P0",
    route: "Base Sepolia / Solana Devnet facilitator",
    proof: "Official no-signup facilitator supports testnet verify and settlement without an API key.",
    nextAction: "Protect one demo API route and settle a reproducible testnet payment.",
    href: "https://docs.cdp.coinbase.com/x402/quickstart-for-sellers",
    updated: "Jul 13, 2026",
  },
  {
    name: "Coinbase Agentic Wallet MCP",
    category: "Wallets",
    stage: "Ready to test",
    priority: "P0",
    route: "Wallet MCP -> spend limits -> x402 request",
    proof: "Official MCP supports service discovery, wallet controls and x402 payments.",
    nextAction: "Install, authenticate and validate a zero-value/read-only flow before funding.",
    href: "https://docs.cdp.coinbase.com/agentic-wallet/mcp/welcome",
    updated: "Jul 13, 2026",
  },
  {
    name: "Cal.com MCP",
    category: "Scheduling",
    stage: "Ready to test",
    priority: "P0",
    route: "Hosted MCP / OAuth 2.1",
    proof: "Hosted server exposes booking, availability and schedule tools without a manual API key.",
    nextAction: "Create an Innovation Day Pass event and complete one reversible booking.",
    href: "https://cal.com/docs/mcp-server",
    updated: "Jul 13, 2026",
  },
  {
    name: "Notion MCP",
    category: "Personal productivity",
    stage: "Credentials needed",
    priority: "P0",
    route: "Official hosted MCP + user OAuth",
    proof: "Notion provides a hosted MCP server, but each user must authorize the workspace they want the agent to access.",
    nextAction: "Connect one test workspace and prove search and read before enabling page creation.",
    href: "https://developers.notion.com/docs/get-started-with-mcp",
    updated: "Jul 14, 2026",
  },
  {
    name: "Trello",
    category: "Personal productivity",
    stage: "Credentials needed",
    priority: "P0",
    route: "Trello REST API + user authorization",
    proof: "Trello exposes boards, lists and cards through its official API; no connection is active in this app yet.",
    nextAction: "Authorize a test board, list cards read-only and create one reversible test card after confirmation.",
    href: "https://developer.atlassian.com/cloud/trello/guides/rest-api/authorization/",
    updated: "Jul 14, 2026",
  },
  {
    name: "Google Calendar",
    category: "Personal productivity",
    stage: "Credentials needed",
    priority: "P0",
    route: "Google OAuth + Calendar API",
    proof: "Calendar access requires Google OAuth consent and narrowly scoped permissions; it is not connected yet.",
    nextAction: "Read availability first, then create and delete one clearly labelled test event with approval.",
    href: "https://developers.google.com/calendar/api/guides/auth",
    updated: "Jul 14, 2026",
  },
  {
    name: "Google Drive",
    category: "Personal productivity",
    stage: "Credentials needed",
    priority: "P1",
    route: "Google OAuth + Drive API",
    proof: "Drive requires OAuth and carefully selected file scopes; the agent currently has no Drive access.",
    nextAction: "Start with user-selected files and metadata search, without broad write or sharing permissions.",
    href: "https://developers.google.com/drive/api/guides/api-specific-auth",
    updated: "Jul 14, 2026",
  },
  {
    name: "Gmail",
    category: "Personal productivity",
    stage: "Credentials needed",
    priority: "P1",
    route: "Google OAuth + Gmail API",
    proof: "Gmail scopes are sensitive and no mailbox is connected; sending mail must never be inferred from chat alone.",
    nextAction: "Begin with explicit search access or draft creation, then require a separate confirmation before sending.",
    href: "https://developers.google.com/gmail/api/auth/scopes",
    updated: "Jul 14, 2026",
  },
  {
    name: "CoinGecko Market Data",
    category: "Portfolio and markets",
    stage: "Ready to test",
    priority: "P0",
    route: "Keyless public API -> optional Demo/Pro API key",
    proof: "Official keyless endpoints support lightweight price and market-data prototypes; production usage needs a dedicated plan and server-side key.",
    nextAction: "Add read-only price lookup and a watchlist before building durable alerts.",
    href: "https://docs.coingecko.com/docs/keyless-public-api",
    updated: "Jul 14, 2026",
  },
  {
    name: "CoinMarketCap Agent Hub",
    category: "Portfolio and markets",
    stage: "Read-only connected",
    priority: "P0",
    route: "Trial Pro keyless API now -> official MCP or x402 next",
    proof: "Live keyless quotes and persistent user watchlists run through CoinMarketCap's official Trial Pro API.",
    nextAction: "Validate usage, request a partner API key and design the official MCP/x402 pilot with CoinMarketCap.",
    href: "https://coinmarketcap.com/api/documentation/",
    updated: "Jul 14, 2026",
  },
  {
    name: "TradingView",
    category: "Portfolio and markets",
    stage: "Research",
    priority: "P1",
    route: "Charts, alert webhooks or broker integration; not general consumer-account OAuth",
    proof: "Official developer APIs focus on chart datafeeds and broker backends rather than unrestricted access to a user's TradingView portfolio.",
    nextAction: "Use CoinGecko or CoinMarketCap for portfolio data first; assess TradingView webhooks only for user-created alerts.",
    href: "https://www.tradingview.com/charting-library-docs/latest/api/",
    updated: "Jul 14, 2026",
  },
  {
    name: "Privy wallet orchestration",
    category: "Wallets",
    stage: "Connected",
    priority: "P0",
    route: "Privy identity + user-owned Stellar wallet",
    proof: "Google login, automatic Stellar wallet creation, Friendbot activation and on-chain Horizon verification are live.",
    nextAction: "Add transaction-scoped signing for the first replay-safe XLM Testnet payment.",
    href: "https://docs.privy.io/",
    updated: "Jul 13, 2026",
  },
  {
    name: "Stripe MCP",
    category: "Payments",
    stage: "Ready to test",
    priority: "P1",
    route: "Remote MCP / OAuth / Stripe Sandbox",
    proof: "Stripe hosts an official MCP with separate sandbox access controls.",
    nextAction: "Connect a sandbox and test customer, product and payment-link creation.",
    href: "https://docs.stripe.com/mcp",
    updated: "Jul 13, 2026",
  },
  {
    name: "Stripe x402",
    category: "Payments",
    stage: "Research",
    priority: "P2",
    route: "Stripe PaymentIntent + x402 facilitator",
    proof: "Stripe documents Base and Base Sepolia behavior, but access remains private preview.",
    nextAction: "Track preview access; do not depend on it for the MVP.",
    href: "https://docs.stripe.com/payments/machine/x402",
    updated: "Jul 13, 2026",
  },
  {
    name: "Square MCP",
    category: "Payments",
    stage: "Credentials needed",
    priority: "P1",
    route: "Hosted MCP beta + Square Sandbox",
    proof: "Block hosts an official MCP for customers, orders, catalog and Square APIs.",
    nextAction: "Create a sandbox application and restrict the first test to catalog and orders.",
    href: "https://developer.squareup.com/docs/mcp",
    updated: "Jul 13, 2026",
  },
  {
    name: "PayPal MCP",
    category: "Payments",
    stage: "Credentials needed",
    priority: "P1",
    route: "Remote MCP / merchant OAuth",
    proof: "PayPal has an official MCP rollout for merchant operations such as invoicing.",
    nextAction: "Confirm sandbox OAuth scopes and test invoice creation without capture.",
    href: "https://developer.paypal.com/community/blog/paypal-model-context-protocol/",
    updated: "Jul 13, 2026",
  },
  {
    name: "Mercado Pago",
    category: "Payments",
    stage: "Research",
    priority: "P1",
    route: "Checkout and payment APIs / custom MCP adapter",
    proof: "Strong LATAM settlement fit, but it requires an application, credentials and a custom adapter.",
    nextAction: "Map test users, checkout preference, webhooks and refund verification.",
    href: "https://www.mercadopago.com/developers/en/docs",
    updated: "Jul 13, 2026",
  },
  {
    name: "Mercado Libre",
    category: "Commerce",
    stage: "Research",
    priority: "P1",
    route: "Marketplace APIs / OAuth / custom MCP adapter",
    proof: "Catalog and order access is strategically relevant in LATAM but not a no-auth MCP connection.",
    nextAction: "Define the smallest seller pilot and required OAuth permissions.",
    href: "https://developers.mercadolibre.com/",
    updated: "Jul 13, 2026",
  },
  {
    name: "BuyWith402",
    category: "Commerce",
    stage: "Research",
    priority: "P1",
    route: "x402 product purchase + fulfillment status",
    proof: "Discovered live in Bazaar with product purchase and order-status endpoints.",
    nextAction: "Audit merchant identity, fulfillment, refunds and duplicate-payment recovery first.",
    href: "https://www.buywith402.com/",
    updated: "Jul 13, 2026",
  },
  {
    name: "x402 Atlas Places",
    category: "Local discovery",
    stage: "Research",
    priority: "P1",
    route: "Paid local-business search APIs via x402",
    proof: "Live Bazaar results advertise Google, Apple and DuckDuckGo local search endpoints.",
    nextAction: "Run one capped payment only after validating output quality and provider identity.",
    href: "https://places.use.x402atlas.com/",
    updated: "Jul 13, 2026",
  },
  {
    name: "Amazon Alexa",
    category: "Voice and home",
    stage: "Research",
    priority: "P1",
    route: "Alexa Custom Skill -> agent-assistant API",
    proof: "Alexa supports custom skills backed by an HTTPS web service.",
    nextAction: "Prototype voice intent -> create_intent -> approval handoff.",
    href: "https://developer.amazon.com/en-US/alexa/alexa-skills-kit/get-deeper/custom-skills",
    updated: "Jul 13, 2026",
  },
  {
    name: "Google Home",
    category: "Voice and home",
    stage: "Research",
    priority: "P2",
    route: "Google Home APIs + mobile authorization",
    proof: "Home APIs expose devices, structures and automations on Android and iOS.",
    nextAction: "Assess account linking and whether commerce intents fit Home automations.",
    href: "https://developers.home.google.com/apis",
    updated: "Jul 13, 2026",
  },
  {
    name: "Samsung SmartThings",
    category: "Voice and home",
    stage: "Research",
    priority: "P2",
    route: "OAuth 2.0 Service Integration",
    proof: "API Access Apps support discovery, control, status and real-time events.",
    nextAction: "Define minimum OAuth scopes and callback endpoints.",
    href: "https://developer.smartthings.com/docs/service-integrations/app-setup",
    updated: "Jul 13, 2026",
  },
  {
    name: "Home Assistant",
    category: "Voice and home",
    stage: "Research",
    priority: "P1",
    route: "Custom integration + Assist intents",
    proof: "Assist pipelines and custom intent handlers can route voice into one component.",
    nextAction: "Prototype a local intent handler calling our remote MCP or REST bridge.",
    href: "https://developers.home-assistant.io/docs/voice/overview/",
    updated: "Jul 13, 2026",
  },
];
