import { z } from "zod";

export const avalancheCapabilityIdSchema = z.enum([
  "avalanche.docs.search", "avalanche.wallet.status", "avalanche.wallet.transfer",
  "dexalot.markets.list", "dexalot.quote.read", "x402.report.purchase",
  "pangolin.swap.avax_to_usdc",
  "circle.cctp.fuji_to_stellar",
  "predictions.sector.read", "predictions.markets.read",
  "avalanche.aave.market.read", "avalanche.aave.position.read",
  "avalanche.nft.collection_read", "avalanche.nft.holder_distribution",
  "avalanche.nft.provenance_read", "avalanche.nft.venue_status",
  "avalanche.nft.floor_read", "defillama.yields.read", "lfj.swap.quote.read",
]);
export type AvalancheCapabilityId = z.infer<typeof avalancheCapabilityIdSchema>;
type Requirement =
  | "privy_session" | "evm_wallet" | "fuji_avax" | "fuji_usdc" | "fuji_wavax"
  | "fuji_nft_owned" | "stellar_wallet" | "stellar_usdc_trustline";
export type AvalancheCapability = {
  id: AvalancheCapabilityId; provider: string; title: string; description: string;
  status: "live" | "ready_to_test" | "planned";
  operation: "read" | "financial" | "cross_chain";
  approval: "none" | "privy_single" | "privy_dual";
  network: "avalanche:fuji" | "avalanche:fuji+stellar:testnet";
  dataScope: "fuji_onchain" | "mainnet_readonly" | "offchain_api";
  requires: readonly Requirement[]; evidence: string; nextAction: string;
};

const capabilities: readonly AvalancheCapability[] = [
  { id: "avalanche.docs.search", provider: "Avalanche Builder Hub MCP", title: "Search official Avalanche knowledge", description: "Search bounded official documentation from the agent.", status: "live", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "offchain_api", requires: ["privy_session"], evidence: "Read-only MCP adapter with an allowlisted docs_search tool.", nextAction: "Ask Carmelita to research an Avalanche integration." },
  { id: "avalanche.wallet.status", provider: "Privy", title: "Inspect the user's Fuji wallet", description: "Return the user-owned EVM address and verified balances.", status: "live", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "fuji_onchain", requires: ["privy_session", "evm_wallet"], evidence: "Privy ownership and Fuji RPC balance checks are implemented.", nextAction: "Ask Carmelita to show the Avalanche wallet and balances." },
  { id: "avalanche.wallet.transfer", provider: "Privy", title: "Send an exact Fuji AVAX amount", description: "Freeze an exact recipient and amount before user signing.", status: "ready_to_test", operation: "financial", approval: "privy_single", network: "avalanche:fuji", dataScope: "fuji_onchain", requires: ["privy_session", "evm_wallet", "fuji_avax"], evidence: "Prepared transaction, receipt verification and replay guards pass automated tests.", nextAction: "Run one small transfer between known Fuji wallets." },
  { id: "dexalot.markets.list", provider: "Dexalot", title: "List Dexalot Testnet markets", description: "Read the deployed Testnet market catalog without a key.", status: "live", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "offchain_api", requires: ["privy_session"], evidence: "Public Testnet catalog adapter is read-only and bounded.", nextAction: "Ask Carmelita to list Dexalot Testnet pairs." },
  { id: "dexalot.quote.read", provider: "Dexalot", title: "Get a non-firm Dexalot quote", description: "Calculate a read-only quote without reserving liquidity.", status: "planned", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "offchain_api", requires: ["privy_session"], evidence: "The adapter and its validation are implemented and tested, but the upstream endpoint returns no quote. Reproduced on 2026-07-31 against api.dexalot-test.com with the exact parameters this connector sends: AVAX/USDC returns {\"success\":false}, and ALOT/USDC and ALOT/AVAX return reasonCode QP-002, \"Circuit Breaker active cannot provide quotes.\" The pair catalog behind dexalot.markets.list still responds, so the two capabilities are not blocked together.", nextAction: "Blocked upstream, not by us. Re-probe /api/rfq/pairprice; promote only once a real quote comes back." },
  { id: "x402.report.purchase", provider: "0xGasless", title: "Purchase an x402 report", description: "Authorize 0.01 Fuji USDC with EIP-3009 and sponsored gas.", status: "live", operation: "financial", approval: "privy_single", network: "avalanche:fuji", dataScope: "fuji_onchain", requires: ["privy_session", "evm_wallet", "fuji_usdc"], evidence: "Settled for real on Fuji on 2026-07-31 in transaction 0x3c03d58756d93da7b8a1409cf621d859c853ed54d710974229e5183cfd9b70ad (block 57475367), independently verified against the RPC: exactly one USDC Transfer of 10000 atomic units from the payer to the frozen payTo, plus an EIP-3009 AuthorizationUsed log burning the nonce. The facilitator sent the transaction; the payer wallet held zero AVAX, so gas sponsorship is measured rather than assumed.", nextAction: "Run a second-user acceptance and replay the paid request: runtime settlement now waits for and persists exact Fuji USDC receipt evidence before delivery." },
  { id: "pangolin.swap.avax_to_usdc", provider: "Pangolin V2", title: "Swap AVAX to Circle USDC", description: "Quote and prepare an exact 0.1 AVAX swap through the pinned Pangolin Fuji router.", status: "ready_to_test", operation: "financial", approval: "privy_single", network: "avalanche:fuji", dataScope: "fuji_onchain", requires: ["privy_session", "evm_wallet", "fuji_avax"], evidence: "Live quote, deployment re-assertion, frozen calldata, policy gate, idempotent preview and receipt verification pass automated tests. No Fuji swap hash has been recorded yet.", nextAction: "Complete one 0.1 AVAX to Circle USDC swap with Privy and save the verified Fuji receipt." },
  { id: "circle.cctp.fuji_to_stellar", provider: "Circle CCTP V2", title: "Bridge USDC from Fuji to Stellar Testnet", description: "Burn on Fuji, verify Circle attestation, then mint and forward on Stellar.", status: "ready_to_test", operation: "cross_chain", approval: "privy_dual", network: "avalanche:fuji+stellar:testnet", dataScope: "fuji_onchain", requires: ["privy_session", "evm_wallet", "fuji_avax", "fuji_usdc", "stellar_wallet", "stellar_usdc_trustline"], evidence: "The resumable state machine and attestation validation pass automated tests.", nextAction: "Complete one end-to-end 1 USDC bridge with two scoped approvals." },
  { id: "predictions.sector.read", provider: "DefiLlama", title: "Read the prediction-market sector by chain", description: "Recompute how much prediction-market TVL exists per chain, including the Avalanche share.", status: "ready_to_test", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "mainnet_readonly", requires: ["privy_session"], evidence: "Public DefiLlama protocols endpoint, filtered by category \"Prediction Market\" and grouped by chain. Reads mainnet TVL by HTTP; no Avalanche chain data is claimed. Repro on 2026-07-31 gave Avalanche $200.4097 across two protocols.", nextAction: "Ask Carmelita which chains carry prediction-market TVL, or run the sector read live." },
  { id: "predictions.markets.read", provider: "Polymarket Gamma", title: "Read live prediction-market prices", description: "Read real mainnet/off-chain market prices from venues that disclose public APIs.", status: "ready_to_test", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "mainnet_readonly", requires: ["privy_session"], evidence: "Public venue endpoints (Polymarket Gamma and CLOB, Kalshi, DefiLlama) reverified keyless on 2026-07-31. Every byte is mainnet or off-chain; the response labels the chain so a Fuji price is never implied.", nextAction: "Ask Carmelita for prediction prices, labeled by venue and chain." },
  { id: "avalanche.aave.market.read", provider: "Aave V3 Fuji", title: "Read Aave V3 Fuji market state", description: "Read reserve configuration and utilization from the live Fuji Pool contract.", status: "ready_to_test", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "fuji_onchain", requires: ["privy_session"], evidence: "eth_call reads against the live Fuji Pool contract. Probed on 2026-07-31: the supply/withdraw path passes all ValidationLogic checks and fails only on probe allowance, proving the asset is not frozen. Aave no longer lists Fuji on its own frontend; this read is our own.", nextAction: "Ask Carmelita for the Aave Fuji market overview. Position read comes separately." },
  { id: "avalanche.aave.position.read", provider: "Aave V3 Fuji", title: "Read the user's Aave V3 Fuji position", description: "Read a user's aToken balance and effective position from the live Fuji Pool.", status: "ready_to_test", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "fuji_onchain", requires: ["privy_session", "evm_wallet"], evidence: "eth_call read of the aToken balance for the user-owned wallet. Makes any future supply demo verifiable back instead of trusting the deposit word.", nextAction: "Ask Carmelita to read the Aave Fuji position for an activated wallet." },
  { id: "avalanche.nft.collection_read", provider: "Glacier / Routescan", title: "Read an NFT collection on Fuji", description: "Read collection, token and metadata from public indexers without a key.", status: "ready_to_test", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "fuji_onchain", requires: ["privy_session"], evidence: "Glacier and Routescan serve Fuji collections and metadata keyless (undocumented tolerance, not a product plan). Attributes/traits exist on Fuji samples but are absent on mainnet collections; only owner-derived analytics are reliable on both.", nextAction: "Ask Carmelita for a Fuji NFT collection overview. Treat missing traits as a data gap, not a flaw." },
  { id: "avalanche.nft.holder_distribution", provider: "Glacier", title: "Read NFT holder concentration", description: "Read holder distribution for a Fuji collection from a public indexer.", status: "ready_to_test", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "fuji_onchain", requires: ["privy_session"], evidence: "ownerAddress-derived analytics survive on both Fuji and mainnet, unlike rarity. The only NFT analytics this project can honestly promise.", nextAction: "Ask Carmelita for holder concentration on a Fuji collection." },
  { id: "avalanche.nft.provenance_read", provider: "Glacier + Routescan", title: "Cross-check NFT provenance", description: "Compare two independent indexers for the same token history.", status: "ready_to_test", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "fuji_onchain", requires: ["privy_session"], evidence: "Two independent Fuji indexers. Disagreement is reported, not resolved; this is also how any future NFT write gets verified.", nextAction: "Ask Carmelita to verify the provenance of a Fuji NFT token." },
  { id: "avalanche.nft.venue_status", provider: "Glacier / Seaport 1.6", title: "Read NFT venue liveness on Fuji", description: "Report which Fuji NFT venues are deployed and configured, without assuming activity.", status: "ready_to_test", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "fuji_onchain", requires: ["privy_session"], evidence: "Preflight for any NFT write. Fuji venues are commercially dead (zero trades since 2023-09-22); \"live\" here means deployed and configured, never active. Joepegs strategy whitelist verified; its proxies are upgradeable by an unmaintained EOA, so Seaport 1.6 (immutable) is the write path.", nextAction: "Ask Carmelita for the Fuji NFT venue status before any NFT action." },
  { id: "avalanche.nft.floor_read", provider: "none", title: "NFT floor price on Fuji", description: "Document-only row: there is no working floor-price source for Avalanche.", status: "planned", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "mainnet_readonly", requires: ["privy_session"], evidence: "OpenSea v2 returns 401 and its instant-key endpoint 404; joepegs.dev 401; Reservoir API closed 2025-10-15; SimpleHash closed 2025-03-27; Moralis lists only Avalanche mainnet 0xa86a. Records the dead ends so nobody reinvestigates them.", nextAction: "Blocked on a human-provided key. Alchemy Fuji is the only plausible unlock; do not re-probe without one." },
  { id: "defillama.yields.read", provider: "DefiLlama", title: "Read yield opportunities by chain", description: "Read mainnet yield contexts from DefiLlama, with the origin chain in the response.", status: "ready_to_test", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "mainnet_readonly", requires: ["privy_session"], evidence: "Public DefiLlama yields endpoint. Never shows a Fuji button next to a mainnet yield number; the chain label is part of the response.", nextAction: "Ask Carmelita for yields on Avalanche mainnet, labeled as such." },
  { id: "lfj.swap.quote.read", provider: "LFJ", title: "Read an LFJ quote (liveness only)", description: "Read a quote from the LFJ aggregator only as a liveness check, never as a price claim.", status: "ready_to_test", operation: "read", approval: "none", network: "avalanche:fuji", dataScope: "offchain_api", requires: ["privy_session"], evidence: "Second-opinion liveness for the Fuji DEX. LFJ quotes its own test USDC, not Circle USDC; a swap presented as buying \"USDC\" would be materially false, so this row never claims price.", nextAction: "Ask Carmelita for an LFJ liveness check, not a price." },
];

export type AvalancheCapabilityContext = { authenticated?: boolean; evmWallet?: boolean; stellarWallet?: boolean; fujiAvax?: boolean; fujiUsdc?: boolean; fujiWavax?: boolean; fujiNftOwned?: boolean; stellarUsdcTrustline?: boolean };
const contextKey = { privy_session: "authenticated", evm_wallet: "evmWallet", stellar_wallet: "stellarWallet", fuji_avax: "fujiAvax", fuji_usdc: "fujiUsdc", fuji_wavax: "fujiWavax", fuji_nft_owned: "fujiNftOwned", stellar_usdc_trustline: "stellarUsdcTrustline" } as const satisfies Record<Requirement, keyof AvalancheCapabilityContext>;
export function listAvalancheCapabilities() { return capabilities.map((capability) => ({ ...capability })); }
export function getAvalancheCapability(id: AvalancheCapabilityId) {
  const capability = capabilities.find((item) => item.id === id);
  if (!capability) throw new Error("avalanche_capability_not_found");
  return { ...capability };
}
export function planAvalancheCapability(id: AvalancheCapabilityId, context: AvalancheCapabilityContext = {}) {
  const capability = getAvalancheCapability(id);
  const blockers = capability.requires.filter((requirement) => context[contextKey[requirement]] !== true);
  return { capability, executable: capability.status !== "planned" && blockers.length === 0, blockers, approvalRequired: capability.approval !== "none", boundary: capability.operation === "read" ? "read_only" : "prepare_then_explicit_privy_approval" } as const;
}


